### ISSUE TITLE
Option to export xlsx

### ISSUE THREAD

**Issue by Lorenitz** [Lorenitz/APIPokemon#1]
## Tasks:

- [x] Argument to tell csv or xlsx
- [ ] Argument helping message
- [ ] Initialize xlsx workbook
- [ ] Write xlsx rows
